# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginPage(self):
    self.driver.get("https://practice.expandtesting.com/login")
    self.driver.set_window_size(1292, 684)
    self.driver.execute_script("window.scrollTo(0,311.6666564941406)")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("practise")
    self.driver.find_element(By.ID, "password").send_keys("SuperSecretPassword!")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-bg").click()
    self.driver.execute_script("window.scrollTo(0,310.4166564941406)")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("practice")
    self.driver.find_element(By.ID, "password").send_keys("Super")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-bg").click()
    self.driver.execute_script("window.scrollTo(0,507.08331298828125)")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("practice")
    self.driver.find_element(By.ID, "password").send_keys("SuperSecretPassword!")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-bg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icon-2x").click()
  
